### ISSUE TITLE
Make a fusebox package

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box-aurelia-loader#4]
Once this one https://github.com/fuse-box/fuse-box/issues/188 got fixed.

**Comment by vegarringdal** [comment]
Maybe Im not following

This repo can be installed by running ```npm install git://github.com/vegarringdal/fuse-box-aurelia-loader --save```

Then you can use it...
Ive tested that it worked before I did the PR

Here its installed:
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/package.json#L26

This in app I just import it before the bootstrapper so that gets used as loader.
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/src/main.ts#L4-L7

Its pretty ok way to do it, if we create a plugin, then it would be to do those 2 imports by default.

**Sample:**
Main issue atm, it that I cant get package to work in sample by getting ```.../src``` and use it
Entry is missing, so just added the file to the sample atm, want to fix this part better

But my break is over, online later today again :-)
